-- AGGREGATE  FUNCTIONS
-- SPECIAL SQL FUNCTIONS THAT PERFORMS A CALCULATION IN MULTIPLE ROWS OF DATA 
-- AND RETURNS ONE SINGAL VALUE AS RESULT
-- WHY WE USE
-- HOW MANY CUSTOMERS WE HAVE
-- WHAT IS THE HIGHEST PAYMENT 
-- WHAT IS THE VAERAGE ORDER values
-- HOW MANY ORDERS PER ORDER STATUS ETC

SELECT * FROM CUSTOMERS;

-- COUNT FUMCTION
SELECT COUNT(*) FROM  CUSTOMERS;

SELECT  COUNT(CUSTOMERNUMBER) AS TOTAL_CUSTOMERS FROM CUSTOMERS;
SELECT COUNT(DISTINCT COUNTRY) AS TOTAL_COUNTRIES FROM CUSTOMERS;

SELECT * FROM PAYMENTS;

-- SUM
SELECT SUM(AMOUNT) AS TOATL_SALES FROM PAYMENTS;

-- MINIMUM  AMOUNT
SELECT MIN(AMOUNT) AS MIN_AMOUNT FROM PAYMENTS;

-- MAXIMUM AMOUNT FROM PAYMENTS
SELECT MAX(AMOUNT) AS MAX_AMOUNT FROM PAYMENTS;

-- AVERAGE FUNCTION


