-- DEPARTMENT TABLE
 
CREATE TABLE DEPARTMENTS(
    DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPT_NAME VARCHAR(50) NOT NULL,
    HOD_NAME VARCHAR(50) NOT NULL,
    HOD_ID INT
 );
 
 INSERT INTO  DEPARTMENTS(DEPT_ID, DEPT_NAME, HOD_NAME, HOD_ID)
 VALUES (101,'MECHATRONICS','PRAVIN KHATKHALE',1);
 INSERT INTO  DEPARTMENTS(DEPT_NAME, HOD_NAME, HOD_ID)
 VALUES ('AIML','DEVYANI JADHAV',2);
 
 SELECT * FROM DEPARTMENTS;
 DROP TABLE DEPARTMENT;