-- SHOW STUDENT ID , NAME, DEPT_ID, DEPT NAME FROM CS
SELECT
     S.STUD_ID, S.STUDENT_NAME, S.DEPT_ID, D.DEPARTMENT_NAME
FROM
     STUDENT S 
     LEFT JOIN
     DEPARTMENT D ON S.DEPT_ID = D.DEPT_ID
     WHERE
     D.DEPARTMENT_NAME = 'AIML';
     
     USE COLLEGE;
     SELECT * FROM STUDENT;
     
     -- CROSS JOIN IS UDES TO CHECK HOW MANY POSSIBLE COMBINATION
     -- WE CAN MAKE ALSO KNOWN AS CARTESIAN PROUCT
     
     
     