create table STUDENTS(
 ROLL_NO INT PRIMARY KEY,
 NAME VARCHAR (100),
GENDER ENUM('MALE','FEMALE','OTHER'),
ELECTIVES SET('PYTHON','JAVA','POWER BI','C','CSS')
);
-- INSERT VALUES
INSERT INTO STUDENTS(ROLL_NO, NAME, GENDER, ELECTIVES)
VALUES
(1,'KAJAL','FEMALE','C,JAVA');
INSERT INTO STUDENTS(ROLL_NO, NAME, GENDER, ELECTIVES)
VALUES
(2,'KOMAL','FEMALE','CSS,JAVA,C');

INSERT INTO STUDENTS(ROLL_NO, NAME, GENDER, ELECTIVES)
VALUES
(3,'VAIBHAV','MALE','CSS,JAVA,C'),
(4,'PRASHANT','MALE','CSS,JAVA,C');

INSERT INTO STUDENTS(ROLL_NO, NAME, GENDER, ELECTIVES)
VALUES
(5,'RUTVIK','MALE','CSS,JAVA,C');

-- ADD NEW COLUMN INFO IN JSON DATA TYPE
ALTER TABLE STUDENTS
ADD COLUMN INFO JSON;-

DESCRIBE STUDENTS;
SELECT * FROM  STUDENTS;