SELECT * FROM STUDENTS;
SELECT * FROM DEPARTMENTS;
-- ADD COLUMN FOR DEPT_ID

-- FOR ADDING FIRST USE 'FIRST' AFER DATATYPE
ALTER TABLE students
ADD COLUMN HOD_ID INT AFTER PHONE;

UPDATE STUDENTS
SET DEPT_ID = 1;

SET SQL_SAFE_UPDATES = 0;

ALTER TABLE students
ADD CONSTRAINT FK_HOD_ID
FOREIGN KEY(HOD_ID)
REFERENCES DEPARTMENTS(HOD_ID);