-- USED UNION

SELECT * FROM STUDENTS_24
UNION
SELECT * FROM STUDENTS_25;

-- USED UNION ALL

SELECT * FROM STUDENTS_24
UNION ALL
SELECT * FROM STUDENTS_25;

-- USED INTERSECTION

SELECT S.NAME, S.CITY FROM STUDENTS_24 S
INNER JOIN STUDENTS_25 T
ON S.ID=T.ID;

SELECT * FROM STUDENTS_25;

SELECT * FROM STUDENTS_24;