CREATE DATABASE COLLEGE
use college;
CREATE TABLE STUDENT(
  DEPT_ID int AUTO_INCREMENT PRIMARY KEY,
  STUDENT_NAME VARCHAR(50),
  STUD_ID INT 
);

INSERT INTO STUDENT(STUDENT_NAME,STUD_ID)
VALUES('KAJAL',101);

INSERT INTO STUDENT(STUDENT_NAME,STUD_ID)
VALUES('KOMAL',102);

INSERT INTO STUDENT(STUDENT_NAME,STUD_ID)
VALUES('RUTUJA',103);

INSERT INTO STUDENT(STUDENT_NAME,STUD_ID)
VALUES('SHRADDHA',104);

INSERT INTO STUDENT(STUDENT_NAME,STUD_ID)
VALUES('SAKSHI',105);

SELECT * FROM STUDENT;

USE COLLEGE;
CREATE TABLE DEPARTMENT(
 DEPT_ID INT AUTO_INCREMENT PRIMARY KEY,
 DEPARTMENT_NAME VARCHAR(50)
);

INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES("AIML"),("CSE"),("CS"),("IT"),("AIDS");

SELECT * FROM DEPARTMENT;
DROP TABLE DEPARTMENT;

-- SHOW STUDENTS WHOSE DEPARTMENT EXISTS IN DEPARTMENT TABLE
       
SELECT 
  S.STUD_ID,
  S.STUDENT_NAME,
  S.DEPT_ID,
  D.DEPARTMENT_NAME
FROM STUDENT S
INNER JOIN DEPARTMENT D
ON S.DEPT_ID = D.DEPT_ID;

SELECT 
  S.STUD_ID,
  S.STUDENT_NAME,
  S.DEPT_ID,
  D.DEPARTMENT_NAME
FROM 
	  STUDENT S
LEFT JOIN 
      DEPARTMENT D
ON
       S.DEPT_ID = D.DEPT_ID;

SELECT 
  S.STUD_ID,
  S.STUDENT_NAME,
  S.DEPT_ID,
  D.DEPARTMENT_NAME
FROM STUDENT S
RIGHT JOIN DEPARTMENT D
ON S.DEPT_ID = D.DEPT_ID;
