SELECT * FROM STUDENTS;
-- ADD COLUMN FOR DEPT_ID

-- FOR ADDING FIRST USE 'FIRST' AFER DATATYPE
ALTER TABLE students
ADD COLUMN DEPT_ID INT AFTER EMAIL;
UPDATE STUDENTS
SET DEPT_ID = 1;

SET SQL_SAFE_UPDATES = 0; 
SELECT * FROM departments;
SELECT DISTINCT DEPT_ID FROM students;

-- TO ESTABLISH RELATIONSHIP USING FOREIGN KEY WE NEED MATCHING COLUMN
-- FOREIGN KEY IS A MATCHING PRIMARY KEY COLUMN FROM PARENT TABLE TO CHILD TABLE

ALTER TABLE students
ADD CONSTRAINT FK_DEPT_ID
FOREIGN KEY(DEPT_ID)
REFERENCES DEPARTMENTS(DEPT_ID);