-- SHOW CUSTOMERS WHO ARE FROM USA AND THEIR
-- CREDITS LIMIT IS MORE THAN 50K


SELECT * FROM CUSTOMERS 
WHERE 
COUNTRY = 'USA' AND CREDITLIMIT > 50000;

-- SHOW ME  CUSTOMERS FROM FRANCE WITH CREDITLIMIT MORE THAN 1 LAKH

SELECT * FROM CUSTOMERS
WHERE COUNTRY = 'FRANCE'
AND CREDITLIMIT > 100000 ;

-- SHOW ME CUSTOMERS WHO ARE FROM USA  AND INDIA 
SELECT * FROM CUSTOMERS WHERE COUNTRY= 'USA'
OR COUNTRY= 'FRANCE'
ORDER BY COUNTRY;

SELECT * FROM PRODUCTS
WHERE NOT (PRODUCTLINE = 'MOTORCYCLES');