-- SHOW STUDENTS WHOSE DEPATMENT EXISTS IN DEPARTMENT TABLE
-- SYNTAX

SELECT S.student_name, D.dept_name
FROM 
	  STUDENTS S
INNER JOIN
	  DEPARTMENTS D
ON 
	  S.DEPT_ID = D.DEPT_ID;
      
SELECT S.student_name, D.dept_name
FROM 
	  STUDENTS S
LEFT JOIN
	  DEPARTMENTS D
ON 
	  S.DEPT_ID = D.DEPT_ID;
      
SELECT S.student_name, D.dept_name
FROM 
	  STUDENTS S
RIGHT JOIN
	  DEPARTMENTS D
ON 
	  S.DEPT_ID = D.DEPT_ID;
      
SELECT S.student_name, D.dept_name
FROM 
	  STUDENTS S
CROSS JOIN
	  DEPARTMENTS D;
 
 SELECT
  S.STUDENT_ID , S.STUDENT_NAME, S.DEPT_ID, D.DEPT_NAME
FROM 
     STUDENTS S
INNER JOIN
	 DEPARTMENTS D
ON S.DEPT_ID = D.DEPT_ID
WHERE DEPT_NAME ='COMPUTER SCIENCE';

 SELECT
  S.STUDENT_ID , S.STUDENT_NAME, S.DEPT_ID, D.DEPT_NAME
FROM 
     STUDENTS S
INNER JOIN
	 DEPARTMENTS D

WHERE DEPT_NAME ='COMPUTER SCIENCE';
     
      