--  RANGE OPERATORS
-- BETWEEN

SELECT * FROM PRODUCTS WHERE BUYPRICE BETWEEN 20 AND 50
order by BUYPRICE;

-- SHOW ME STOCK BETWEEN 2K TO 4K
SELECT * FROM PRODUCTS 
WHERE QUANTITYINSTOCK BETWEEN 2000 AND 4000
ORDER BY PRODUCTNAME;

SELECT * FROM CUSTOMERS
WHERE COUNTRY IN('USA','FRANCE', 'SPAIN');

-- SHOW ME CUSTOMERS FROM 'BARCELONA', 'BOSTON', 'PARIS';
SELECT * FROM CUSTOMERS
WHERE CITY IN('BARCELONA', 'BOSTON', 'PARIS');
