CREATE DATABASE RANDOM;
USE RANDOM;
CREATE TABLE EMPP(
   EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
   EMP_NAME VARCHAR(50)
);

INSERT INTO EMPP(EMP_ID, EMP_NAME)
VALUES (1,'KAJAL');

INSERT INTO EMPP(EMP_NAME)
VALUES ("RUTUJAA"),("PRIYA"),("KOMAL");

DELETE FROM EMPP;

INSERT INTO EMPP(EMP_NAME)
VALUES ("SHRAVANI");

TRUNCATE TABLE EMPP;

INSERT INTO EMPP(EMP_NAME)
VALUES ("PAYAL");
SET SQL_SAFE_UPDATES=0;
SELECT * FROM EMPP;

-- WHY  TRUNCATE IS DDL COMMAND IF IT IS BEHAVING LIKE DELETE

-- TRUNCATE SIMPLY DROPS THE TABLE AND CREATE IT AGAIN WITH ALL THE FEATURES
-- IT ALSO RESETS THE AUTO_INCREMENT FEATURES WHICH IS RELATED TO TABLE STRUCTURE

-- WRITE DIFFERENCE BETWEEEN  TRUNCATE, DELETE AND DROP AS PER YOUR UNDERSTANDING
