-- PATTERN MACHING OPERSATORS
-- 1% IT MATCHES SEQUENCE OF CHARACTERS
-- 2.- IT MATCHES ONLY ONE CHARACTER
-- USED WITH LIKE OPERATOR
-- SHOW ME CUSTOMERS WHO'S NAME STARTS WITH 'A'

SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%';

-- SHOW ME CUSTOMERS FROM COUNTRY WHERE NAME STARTS WITH 'U'
 -- NUMBER OF UNDERSCORE GIVES THAT NUMBER OF VALUE FROM DATASET
SELECT * FROM CUSTOMERS WHERE COUNTRY LIKE '_____';

-- STARTS WITH START LETTER AND ENDS WITH NUMBER OF UNDERSCORE BY VALUE
SELECT * FROM CUSTOMERS WHERE COUNTRY LIKE 'U__';

--  END WITH THE LAST LETTER
SELECT * FROM CUSTOMERS WHERE COUNTRY LIKE '%D';
SELECT * FROM CUSTOMERS WHERE COUNTRY LIKE '_____d';

-- SHOW ME CUSTOMERS WITH CITY NAME HAVING K
SELECT * FROM CUSTOMERS WHERE CITY LIKE '%K%';



